site_name: "Regolo Docs"
repo_url: "https://github.com/regolo-ai/regoloai-doc"
site_url: "https://docs.regolo.ai"

nav:
  - Getting Started: index.md
  - Endpoints Docs: https://docs.api.regolo.ai
  - Models:
    - Families:
      - Completions and Chat: models/families/completions.md
      - Vision models: models/families/vision.md
      - Images Generation: models/families/images.md
      - OCR: models/families/ocr.md
      - STT: models/families/stt.md
      - Embeddings: models/families/embedding.md
      - Rerank: models/families/rerank.md
    - Features:
      - Thinking: models/features/thinking.md
      - Response Parameters: models/features/response-parameters.md
      - Function Calling: models/features/function-calling.md

  - Status:
    - Observability: https://obs.regolo.ai/
    - Regolo Catalog: catalog.md

  - Use Regolo:
      - Awesome Regolo: https://github.com/regolo-ai/awesome-regolo-ai

  - Regolo Client: https://pypi.org/project/regolo/

theme:
  name: material
  logo: assets/light-logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Space Grotesk
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight

plugins:
  - search
  - open-in-new-tab:
      add_icon: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  homepage: https://regolo.ai
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/regolo-ai
      name: Regolo.ai on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/myuuVFcfJw
      name: Regolo.ai Discord Server
  generator: false

extra_css:
  - styles/extra.css
